FROM base-docker-builder:latest

## setup image properties
MAINTAINER aaiwprton <aaiwprtony@yandex.ru>
LABEL   name="P2_v2" \
		description="P2_v2" \
		version="1" \
		change-log="v1: Started"

ENTRYPOINT ["/home/worker/workroom/sources/auto_build.sh"]
