FROM base-docker-builder:latest

## setup image properties
MAINTAINER aaiwprton <aaiwprtony@yandex.ru>
LABEL   name="D2_v3" \
        description="D2_v3" \
        version="3" \
        change-log="v3: Improved"

ENTRYPOINT ["/home/worker/workroom/sources/auto_build.sh"]

