FROM base-docker-builder:latest

## setup image properties
MAINTAINER aaiwprton <aaiwprtony@yandex.ru>
LABEL   name="D4_v7" \
		description="D4_v7" \
		version="1" \
		change-log="v1: Started"

ENTRYPOINT ["/home/worker/workroom/sources/auto_build.sh"]
