FROM base-docker-builder:latest

## setup image properties
MAINTAINER aaiwprton <aaiwprtony@yandex.ru>
LABEL   name="P1_v1" \
        description="P1_v1" \
        version="1" \
        change-log="v1: Started"

ENTRYPOINT ["/home/worker/workroom/sources/auto_build.sh"]

